name: AD_DNA_Seq
channels:
  - anaconda
  - r
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcftools=1.20
  - bedtools=2.31.1
  - bioconductor-limma=3.58.1
  - biopython=1.85
  - htslib=1.20
  - ipykernel=6.29.5
  - jupyter=1.0.0
  - make=4.4.1
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - minimap2=2.1.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - pandas=2.2.2
  - parasail-python=1.3.4
  - polars=1.6.0
  - rpy2=3.5.11
  - scipy=1.13.1
  - pysam=0.22.1
  - python=3.12.5
  - r-base=4.3.3
  - r-statmod=1.5.0
  - seaborn=0.13.2
  - statsmodels=0.14.2
